version: "3.9"
services:
  groups:
    image: stoplight/prism
    ports:
      - "8001:8001"
    volumes:
      - ./groups.yml:/groups.yml
    command: mock -h 0.0.0.0 -p 8001 -d /groups.yml
  commands:
    image: stoplight/prism
    ports:
      - "8002:8002"
    volumes:
      - ./commands.yml:/commands.yml
    command: mock -h 0.0.0.0 -p 8002 -d /commands.yml
  obs:
    image: stoplight/prism
    ports:
      - "8003:8003"
    volumes:
      - ./obs.yml:/obs.yml
    command: mock -h 0.0.0.0 -p 8003 -d /obs.yml
