version: "3.9"
services:
  groups:
    image: stoplight/prism
    ports:
      - "8001:8001"
    volumes:
      - ./obs-chatbot-groups.yml:/api.yml
    command: mock -h 0.0.0.0 -p 8001 -d /api.yml
  commands:
    image: stoplight/prism
    ports:
      - "8002:8002"
    volumes:
      - ./obs-chatbot-commands.yml:/api.yml
    command: mock -h 0.0.0.0 -p 8002 -d /api.yml
  obs:
    image: stoplight/prism
    ports:
      - "8003:8003"
    volumes:
      - ./obs-chatbot-obs.yml:/api.yml
    command: mock -h 0.0.0.0 -p 8003 -d /api.yml