openapi: '3.0.2'

x-json-schema-faker:
  locale: en
  min-items: 2
  max-items: 10
  resolve-json-path: true

info:
  title: OBS Chatbot - Groups
  version: '1.0'
  description: In OBS Chatbot, groups can be used to customize which viewers are allowed to execute different commands.
servers:
  - url: http://localhost:8001
    description: "Development"

paths:
  /groups:
    get:
      summary: List available groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/groups'
  /groups/{id}:
    get:
      summary: View a single group
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '404': 
          $ref: '#/components/responses/NotFound'
    put:
      summary: Create or update a group
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: "#/components/responses/Error"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/group'
    delete:
      summary: Delete a group. Does not delete users as a side-effect
      responses: 
        '204':
          description: Delete successful

components:
  schemas:
    groups:
      type: array
      items:
        $ref: '#/components/schemas/group'
    group:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-faker: random.word
        description:
          type: string
          x-faker: random.lorem.sentence
    errors:
      type: object
      properties:
        id:
          type: string
          format: uuid
        timestamp: 
          type: string
          format: date-time
        errors:
          type: array
          items:
            $ref: '#/components/schemas/error'
    error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        
  responses:
    'Success': 
      description: Operation completed successfully, and returns a group
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/group'
    'NoContent':
      description: Operation completed successfully, with no content
    'NotFound':
      description: 'Group not found'
    'Error':
      description: Operation failed with 1 or more errors
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
